version: '3.8'

services:
  kilo-app:
    build: .
    ports:
      - "3000:3000"  # Frontend
      - "8080:8080"  # Flask API
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
